export * from "./Hero";
export * from "./ExtraInfo";
export { default as Home } from "./Home";
export { default as Chart } from "./Chart";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as Button } from "./Button";
export { default as Loader } from "./Loader";
export { default as Gallery } from "./Gallery";
export { default as Tooltip } from "./Tooltip";
export { default as Benefits } from "./Benefits";
export { default as Timeline } from "./Timeline";
export { default as ButtonAnim } from "./ButtonAnim";
export { default as ModalContact } from "./ModalContact";
export { default as ModalMendoza } from "./ModalMendoza";
export { default as NuestroEquipo } from "./NuestroEquipo";
export { default as ButtonChatbot } from "./ButtonChatbot";
export { default as ButtonWhatsapp } from "./ButtonWhatsapp";
export { default as SliderNosotros } from "./SliderNosotros";
export { default as PageTransition } from "./PageTransition";
export { default as InappropriateDevice } from "./InappropriateDevice";
